### ISSUE TITLE
Merge current features with each other

### ISSUE THREAD

**Issue by Leo-Wolff** [Leo-Wolff/SandScript#21]

**Comment by Leo-Wolff** [comment]
I worked on the drafts feature within my branch. The current functionalities are now possible:
Delete a draft by clicking an img element that is tied to it
Post a new draft by various buttons (when exiting and "saving as draft", when signing or not signing)

I'm currently working on showing the draft data within Quill, from there I'll try to make it work so that when a user clicks on a draft item it shows the draft data in the letter editor and finally that when saving again the draft will update

**Comment by Kboere** [comment]
@Leo-Wolff and I worked on mergeing all the filters to the development branch. Yesterday me and @enisokic did the matching and filtering part. 

Happy to say that everything works together! just some minor tweaks are needed and some tidy-up to do, but we are almost there

**Comment by Kboere** [comment]
Merge has been completed! Some bugs where formed but fixed that! Project works!
