### ISSUE TITLE
Improve Draft feature

### ISSUE THREAD

**Issue by Leo-Wolff** [Leo-Wolff/SandScript#23]
Improvements to be made:
- Delete drafts
- Make the draft item clickable and send that data to the text editor page for editing
- Update drafts
- Make all buttons functional (including updating and inserting drafts)
- Bottle editor page HTML, CSS, and JS

**Comment by Leo-Wolff** [comment]
When you click on a draft item now you will see it in the text editor! (and if you open a text editor without a draft existing yet, it will just load normally)

Tomorrow I will look into making the draft data update. Shouldn't be that hard to pull off but we'll see

**Comment by Kboere** [comment]
done!
