### ISSUE TITLE
Wiki Configuration + Concept + Process

### ISSUE THREAD

**Issue by Leo-Wolff** [Leo-Wolff/SandScript#3]
Translate all of the text into English and format it so that it fits the current project context (pay attention to the flow of the wiki and that the story can be followed easily).

Finish design and wireflow of app (and documentate this as well)

**Comment by Leo-Wolff** [comment]
@enisokic for the documentation i need a flow with the screens you've made (basically that shows the connection between all of the pages). And the style tile that you made. Can you throw the files in here or in teams? Thanks!

**Comment by Leo-Wolff** [comment]
Text will take some time to write and will be done later in the week:
- Job stories about the entire concept, not just focused around the draft feature
- Requirement list about the entire concept, not just focused around the draft feature
- Task division, still need a clear understanding of Robin's role within the project
- We haven't really decided on any settings for ESLint. So I have just written some plain text saying that we use it without much elaboration
- I have set up the page structure for our weekly log. But obviously we can't fully fill it in just yet

**Comment by Kboere** [comment]
Things to be done:

- Job stories about the entire concept, not just focused around the draft feature
- Requirements which "would", "should" or "could" have been nice to add to the app. The "Musts" have already been written
- We haven't really decided on any settings for ESLint. So I have just written some plain text saying that we use it without much elaboration
- All of us need to update their weekly log in the wiki

**Comment by Kboere** [comment]
Things to be done:

- Requirements which "would", "should" or "could" have been nice to add to the app. The "Musts" have already been written
- We haven't really decided on any settings for ESLint. So I have just written some plain text saying that we use it without much elaboration
- All of us need to update their weekly log in the wiki

**Comment by Kboere** [comment]
All is done! jiust some extar things to do now is what we could have done if we had more time.
