### ISSUE TITLE
Connect matches to drafts feature

### ISSUE THREAD

**Issue by Leo-Wolff** [Leo-Wolff/SandScript#30]
My feature is almost finished in terms of functionalities (should at least be wrapped up soon). The only thing I still need to do is connect my feature to the matches feature (so in the case where you get a new match and then proceed to write a letter to them, the information of the match gets tied to the letter that is being written. With this connection I should also be able to make a profile overview of the recipient match)

Since I have worked very little on that side of the database myself, I would like some help with this because 1. I don't know/understand much about what goes on there and 2. I don't want to accidentally break someone else's code with whatever I do

Is anyone available for this either this Sunday or sometime next week?

**Comment by Kboere** [comment]
Matching is connected correctly with the merging we did today! Yesterday me @enisokic and @Leo-Wolff had a little meeting on how to approach this issue.

Luckily Leo found some help and managed to connect a match to the drafts feature.

**Comment by Kboere** [comment]
merged with development and works!
