### ISSUE TITLE
Feature: Integrate Drafts

### ISSUE THREAD

**Issue by Leo-Wolff** [Leo-Wolff/SandScript#6]
Integrate drafts feature within the concept. For now, this can be done with fake data within the app.

**Comment by Leo-Wolff** [comment]
What I have done so far and what still needs doing:
So far the text editor completely works with HTML and CSS and data can be fetched properly. Posting does not work yet nor does the posting send any data to the database

HTML and CSS looks good for drafts. The only thing that still needs doing is make it so that the data is dynamic (and also fetches that data from the database). I'll have to figure out how ejs works first though

**Comment by Kboere** [comment]
merged!
